name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project
        run: zip -r pid.zip src/PIDController
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "pid.zip"
          files: "./src/pid.zip"
      - name: Install foreman
        uses: Roblox/setup-foreman@v1
        with:
          version: "^1.0.0"
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Model file
        run: rojo build -o PIDController.rbxmx
      - name: Publish to Roblox
        shell: bash
        env:
          REMODEL_AUTH: ${{ secrets.RBX_AUTH }}
        run: remodel run publish